### ISSUE TITLE
Inserting change set filename into database change log results in build failure for long file paths

### ISSUE THREAD

**Issue by eamason9629** [tlberglund/gradle-liquibase-plugin#16]
We're getting the following error:
Liquibase Update Failed: ORA-12899: value too large for column "SCHEMA"."DATABASECHANGELOG"."FILENAME" (actual: 203, maximum: 200)

Would it be possible to truncate the filename and have this be a warning instead of a build failure?

Or, since we're providing the files in the change log as relative, only have the relative path instead of the full path? That's what's really causing this failure.

**Comment by stevesaliman** [comment]
Liquibase has made the filename column of the databasechangelog table 255 charcters in a later release.  The Gradle Liquibase plugin now supports Liquibase 3.3.2, so this problem should be fixed for now.
