### ISSUE TITLE
namepace the liquibase tasks

### ISSUE THREAD

**Issue by kyleboon** [tlberglund/gradle-liquibase-plugin#20]
I feel like some of the liquibase tasks have common task names (update for example) and it would be useful to have them namespaced.

```
gradle update
```

to 

```
gradle db-update
```

**Comment by stevesaliman** [comment]
I switch java versions a lot when I test things, and must have uploaded the last snapshot after compiling with Java 8.

I just recompiled and uploaded a new snapshot with explicit support for Java 1.5 and above.  Things should be working now.
