### ISSUE TITLE
Add diffChangeLog Gradle task

### ISSUE THREAD

**Issue by petermetz** [tlberglund/gradle-liquibase-plugin#23]
Hi,

Thanks for the plugin, it is awesome! 

I wanted to set up an automated schema updating mechanism with the help of 'diffChangeLog' and 'update'.

Is there any chance that the missing 'diffChangeLog' task will make it to the plugin?

Kind regards,
Peter

**Comment by stevesaliman** [comment]
I do intend to keep this plugin up to date with the changes made in Liquibase itself, adding new options to the plugin as they are added to Liquibase.  Unfortunately, some changes made in version 3.2 have caused issues that prevent me from updating to it.  I've created [JIRA 1968](https://liquibase.jira.com/browse/CORE-1968) for it, but I'm kind of stuck until that gets resolved.

Steve

**Comment by stevesaliman** [comment]
Version 1.0.1 of the plugin now supports Liquibase 3.3.2, including support for the diffChangeLog task.  FYI, I've heard that Liquibase itself has an issue with the diffChangeLog task in its latest release (https://github.com/tlberglund/groovy-liquibase/pull/45).
