### ISSUE TITLE
option to allow XML for changelogs

### ISSUE THREAD

**Issue by sbuettner** [tlberglund/gradle-liquibase-plugin#26]
Hi,
first, thanks for creating this plugin.

Is there a plan to allow xml to be used as the output format? This would simplify the integration with systems like spring boot which use the xml based approach.

Maybe one way could be to use the suffix of the changelog file to determine the format like the grails plugin does: http://grails-plugins.github.io/grails-database-migration/docs/manual/ref/Rollback%20Scripts/dbm-generate-changelog.html

**Comment by stevesaliman** [comment]
All of the real work is done by Liquibase itself, and Liquibase already handles differente types of files based on extension.  The plugin simply registers the Groovy DSL as a valid parser for .groovy files, then calls Liquibase to execute whatever tasks you choose.  If the the ```changeLogFile``` in build.gradle ends with .groovy, Liquibase will use the Groovy DSL that the plugin registerred, but if it ends with .xml, it will simply use its own XML parser to interact with the change log file.  If you use .yaml as an extension, it will deal in YAML files, etc.

**Comment by sbuettner** [comment]
Great, 
by just looking at the plugin documentation i  thought it was just supporting the groovy dsl. 

Thank you.

**Comment by stevesaliman** [comment]
It looks like there is a shortcoming in the documentation.  I'll correct it in the next release.
