### ISSUE TITLE
merge with liquibase fork

### ISSUE THREAD

**Issue by landsman** [tlberglund/gradle-liquibase-plugin#31]
Hello,

can you image that [official fork](https://github.com/liquibase/liquibase-gradle-plugin) will be merged to your repository and you'll move it under `liquibase` org?

This fork makes things more complicated and It would be nice to make it "official".

What do you think?

**Comment by stevesaliman** [comment]
The official fork was created from this repository when tlberglund handed over the development of the Gradle plugin.  This repository is no longer maintained, so it doesn't make sense to merge anything into it.

**Comment by landsman** [comment]
I do understand this. But it doesn't look right that there is an official plugin as a fork. It can be fixed - that is what I suggest.

Also, it does complicate things: for example, just creating PR by a new contributor to "fork from fork" feels wrong, you have to click many times to do it.

Please consider making this pretty.

**Comment by stevesaliman** [comment]
The code won't be merged into this repository.  At best, we could unlink the official repo from this one.

I had considered making a fresh copy and using that as the official repository when we first moved the code to the liquiabse space, but I wanted to give tlberglund credit for originating this effort.

**Comment by landsman** [comment]
> I wanted to give tlberglund credit for originating this effort.

I understand that, of course, but it looks really weird. It doesn't inspire confidence in me as a stable solution. 
The credit will definitely stay with him - he won't disappear from the git log and contributors! :)

Please try to reconsider and make this fork: https://github.com/liquibase/liquibase-gradle-plugin a classic repository.

GitHub also offers the ability to move personal repositories under an organization.
That's why I offered this as a first possible solution. I believe that would have been the best possible way at the time you did the fork.

**Comment by landsman** [comment]
Do you see a way in here?

**Comment by landsman** [comment]
@stevesaliman Can you please revisit this? Every time [I visit the official repository](https://github.com/liquibase/liquibase-gradle-plugin) I think that I went to someone's fork and I am in the wrong place... It's weird.

**Comment by tlberglund** [comment]
I am 100% fine with the fork being decoupled from this repo, and I can switch this repo to private. I would rather the project be clear and usable than have credit at this point. :)
